### PR TITLE
push docker images to private fabric8 docker registry

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by cmoulliard** [comment]
Will this fix resolve this issue that I have experimented with a jenkins job ?

```
[INFO] --- docker-maven-plugin:0.13.6:build (default-cli) @ demo2 ---
[INFO] Copying files to /var/jenkins_home/workspace/gogsadmin-demo2/target/docker/fabric8-docker-registry.null/80/fabric8/demo2/1.0.3/build/maven
[INFO] Building tar: /var/jenkins_home/workspace/gogsadmin-demo2/target/docker/fabric8-docker-registry.null/80/fabric8/demo2/1.0.3/tmp/docker-build.tar
[INFO] DOCKER> [fabric8-docker-registry.null:80/fabric8/demo2:1.0.3] : Built image 491f95914fd5
[INFO] 
[INFO] --- docker-maven-plugin:0.13.6:push (default-cli) @ demo2 ---
[INFO] DOCKER> ... The push refers to a repository [fabric8-docker-registry.null:80/fabric8/demo2] (len: 1)
[ERROR] DOCKER> unable to ping registry endpoint https://fabric8-docker-registry.null:80/v0/
v2 ping attempt failed with error: Get https://fabric8-docker-registry.null:80/v2/: dial tcp: lookup fabric8-docker-registry.null: no such host
 v1 ping attempt failed with error: Get https://fabric8-docker-registry.null:80/v1/_ping: dial tcp: lookup fabric8-docker-registry.null: no such host 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by rawlingsj** [comment]
Ah it's actually cause the issue!  The problem is script changes take effect immediately and this change requires a release.. I'll revert this until the release has happened!

**Comment by cmoulliard** [comment]
So I have to wait next release

**Comment by rawlingsj** [comment]
Nope - I've just reverted the change.  Can you retry please?

**Comment by cmoulliard** [comment]
Do I have to create a new CD Pipeline project to test it ?

**Comment by rawlingsj** [comment]
no you can just re-trigger the jenkins job

**Comment by rawlingsj** [comment]
it will clone the workflow scripts... I think we could tag the workflow scripts at release time to ensure they dont change.

**Comment by rawlingsj** [comment]
issue raised to prevent updates to workflow scripts affecting a release https://github.com/fabric8io/fabric8/issues/5073

**Comment by cmoulliard** [comment]
Thx. Build is working now.

**Pull request merged**
