### PR TITLE
Use Maven version 3.3.9 installation in Maven install workflow

### LINKED ISSUE #154: Use Maven version 3.3.9 installation in Maven install workflow

### PR DESCRIPTION
**Pull request by astefanutti**
Fixes #154

### CODE REVIEW

**Comment by jstrachan** [comment]
[merge]

**Comment by astefanutti** [comment]
Note that it requires fabric8io/jenkins-docker#77.

**Comment by rawlingsj** [comment]
@astefanutti FWIW if the aim is to update all the other Java pipelines to use a newer version of maven then you'll need to update the maven builder image https://github.com/fabric8io/maven-builder

**Comment by jimmidyson** [comment]
@rawlingsj Maven builder image uses 3.3.9 already - https://github.com/fabric8io/maven-builder/blob/master/Dockerfile#L19-L26 - although not sure if Docker image has been published with those changes?

@jstrachan This repo doesn't have any CI builds set up so manual merges I'm afraid.

**Comment by astefanutti** [comment]
@rawlingsj, @jimmidyson, from my understanding, the `install` Maven workflow in its current form does not use the Maven builder image but rather rely on the Maven tooling configuration from the Jenkins image.

**Pull request closed without merging**
